spring:
  kafka:
    listener:
      ack-mode: MANUAL_IMMEDIATE
      type : SINGLE
    consumer:
      bootstrap-servers: localhost:29092
      #group-id: cdc_group
  application:
    name: query-service
  data:
    mongodb:
      uri: mongodb://root:root@127.0.0.1:27017/?readPreference=primary&replicaSet=rs0&directConnection=true

#      uri: mongodb://localhost:27017/?readPreference=primary&replicaSet=rs0&authMechanism=DEFAULT&directConnection=true/sdc_test
      databaseName: sdc_test
      username: root
      password: root
      authentication-database: admin
      database: sdc_test

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

server:
  port: 9001

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, busrefresh, info, prometheus, metrics